apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: ci
          image: htech7x/argo-web:web-6ad81bb7cd2edeab8363f63d3a7f49266126b889
---
apiVersion: v1
kind: Service
metadata:
  name: ci-svc
spec:
  selector:
    app: cicd
  ports:
    - port: 80
      targetPort: 80
  type: NodePort


