apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: ci
          image: htech7x/argo-web:web-a71c9f383e61ec77b1f2e1160e59f4e56a260e4e
---
apiVersion: v1
kind: Service
metadata:
  name: ci-svc
spec:
  selector:
    app: cicd
  ports:
    - port: 80
      targetPort: 80
  type: NodePort


