apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: ci
          image: htech7x/argo-web:web-5cc1a7f81667ed016e7562967361ce5958b9dcb0
---
apiVersion: v1
kind: Service
metadata:
  name: ci-svc
spec:
  selector:
    app: cicd
  ports:
    - port: 80
      targetPort: 80
  type: NodePort


