apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
        - name: ci
          image: htech7x/argo-web:web-67c90fc0605985d14b38edfc0bda853c97ba50e0
---
apiVersion: v1
kind: Service
metadata:
  name: ci-svc
spec:
  selector:
    app: cicd
  ports:
    - port: 80
      targetPort: 80
  type: NodePort


