name: Test CI/CD

on:
  push:
    branches:
      - main

jobs:
  # build:
  #   runs-on: ubuntu-latest
  #   steps:
    
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Copy custom code
  #     run: |
  #       # Copy code from custom_folder into the source folder
  #       #ls -la src/
  #       #cp -r custom_folder/* src/
  #       #ls -la src/
  #       #ls -la
  # test:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:

  #   - name: Running test
  #     run: |
  #       ls -la
  
  build-docker-image:
    #needs: [build,test]  # <--- this tells that previous step(name "build") should be done before this one
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USER }} # repo -> "Settings" -> "Secrets and variables"
        password: ${{ secrets.DOCKERHUB_PASSWD }} # repo -> "Settings" -> "Secrets and variables"
        #password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Login to Github # --> https://github.com/docker/login-action#github-container-registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GIT_TOKEN }}
      
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKERHUB_USER }}/argo-web:web-${{ github.sha }}
        #tags: htech7x/argo-web:web
  update-manifest-argocd:
    needs: build-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: changing the deployment of git repo
        with:
          repository: 'htech7x/my-ci-cd'
          token: ${{ secrets.GIT_TOKEN }}
      - name: setup git config
        run: |
          git config --global user.email htech7x@gmail.com
          git config --global user.name htech7x
          echo ${{ github.sha }}
          ls -la
          pwd
          cat k8s_deploy/deploy.yaml
          pwd

          echo "XXXXXXXXXX"
          echo ${{ github.actor }}
          # sed -i 's/image: nginx/image: ${{ github.actor }}/argo-web:web-${{ github.sha }}/g' k8s_deploy/deploy.yaml
          # sed -i "s/image: nginx/image: ${{ github.actor }}/argo-web:web-${{ github.sha }}/g" k8s_deploy/deploy.yaml
          sed -i 's/${{ github.actor }}.*/${{ github.actor }}\/argo-web:web-${{ github.sha }}/g" k8s_deploy/deploy.yaml
          cat k8s_deploy/deploy.yaml
          echo "XXXXXXXXXX"
          git add .
          git commit -m 'Done  by Github Actions Job changemanifest: ${{ github.run_number }}'
          git push origin main
        env:
          GIT_USERNAME: ${{ secrets.GIT_USER }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWD }}
          RUN_NUMBER: ${{ github.run_number }}
